#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1";
IMAGE="$2";
HOSTNAME=$(hostname -f);

if [ -f $DOKKU_ROOT/$APP/ENV ];then
  if grep SLACK_NOTIFY $DOKKU_ROOT/$APP/ENV ; then
    unset SLACK_NOTIFY
    eval `grep SLACK_NOTIFY $DOKKU_ROOT/$APP/ENV`
  fi
fi

if [ "$SLACK_NOTIFY" == 1 ]; then

  if [ -f $DOKKU_ROOT/$APP/ENV ];then
    if grep SLACK_CHANNEL $DOKKU_ROOT/$APP/ENV ; then
      unset SLACK_CHANNEL
      eval `grep SLACK_CHANNEL $DOKKU_ROOT/$APP/ENV`
    fi
  fi


  echo "-----> Notifying Slack ..."
  echo ":ship: Deployed $APP to $HOSTNAME via `cat $DOKKU_ROOT/$APP/URL`" | $PLUGIN_PATH/dokku-slack/slack-notify
fi
